# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'authGoogleFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for authGoogleFirebase
  pod 'FirebaseCore'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn', '~> 5.0'
  
end

